baseURL: https://www.generatecoll.com
title: Chris Ried Portfolio
defaultContentLanguage: en
theme: eternity
googleAnalytics: ''
params:
  image: /images/banner.png
  logo: logo.png
  subtitle: Portfolio of Chris Ried
  copyright: All rights reserved.
  author: Chris Ried
  dontShowSource: false
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 6
        people: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 1
  socials:
    - icon: far fa-envelope fa-lg
      url: mailto:chris.ried@cbayes.com
      landing: true
    - icon: fab fa-github fa-lg
      url: https://github.com/cdr6934
      landing: true
    - icon: fab fa-instagram fa-lg
      url: https://instagram.com/generate.collective
    - icon: fab fa-linkedin-in fa-lg
      url: https://www.linkedin.com/in/chrisried/
  homepage: /work
  specialPages:
    - work
    - archive
    - about
  bypassWelcomePage: true
  disableWelcomePageBackground: false
  plausible: ''
  disableRadius: false
  moveIt: false
  disableAlwaysResize: false
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
taxonomies:
  tag: tags
permalinks:
  work: ':filename/'
menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: generative
      url: /tags/generative/
      weight: 2
    - name: photography
      url: /tags/photography/
      weight: 3
    - name: writing
      url: /tags/writing/
      weight: 4
    - name: public
      url: /public_work/
      weight: 5
    - name: portfolio
      url: /portfolio/
      weight: 6
    - name: about
      url: /about/
      weight: 7
    - name: newsletter
      url: https://generative.substack.com/
      weight: 8